
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 05 19:31:21 CST 2025
//----------------------------------------------------

package Actividad7;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 29;
  public static final int IDENTIFIER = 69;
  public static final int FROM = 28;
  public static final int LESS_THAN = 50;
  public static final int GREATER_THAN = 51;
  public static final int ASYNC = 34;
  public static final int RAISE = 20;
  public static final int NONLOCAL = 33;
  public static final int LAMBDA = 24;
  public static final int PASS = 16;
  public static final int INDENT = 40;
  public static final int STRING_SIMPLE = 73;
  public static final int COMMA = 58;
  public static final int DEDENT = 41;
  public static final int RBRACE = 60;
  public static final int CAST_BOOL = 79;
  public static final int ELIF = 11;
  public static final int RPAREN = 66;
  public static final int INTEGER = 70;
  public static final int LBRACE = 59;
  public static final int LPAREN = 65;
  public static final int DEL = 30;
  public static final int YIELD = 25;
  public static final int FALSE = 75;
  public static final int NOT = 7;
  public static final int DEF = 22;
  public static final int MATCH = 67;
  public static final int FLOAT = 71;
  public static final int PACKAGE = 36;
  public static final int CLASS = 26;
  public static final int EXCEPT = 18;
  public static final int MULTIPLY = 45;
  public static final int PIPE = 64;
  public static final int MALFORMED_NUMBER = 81;
  public static final int TRUE = 74;
  public static final int PLUS = 42;
  public static final int DIVIDE = 46;
  public static final int WHILE = 13;
  public static final int EQUAL = 47;
  public static final int MODULE = 54;
  public static final int LINE_COMMENT = 37;
  public static final int NONE = 4;
  public static final int FOR = 12;
  public static final int RETURN = 23;
  public static final int BACK_SLASH = 63;
  public static final int ELSE = 10;
  public static final int TRY = 17;
  public static final int BREAK = 14;
  public static final int CAST_STR = 78;
  public static final int DOT = 55;
  public static final int EOF = 0;
  public static final int SEMICOLON = 56;
  public static final int MALFORMED_IDENTIFIER = 82;
  public static final int UNCLOSED_STRING = 80;
  public static final int THIS = 2;
  public static final int DEFAULT = 83;
  public static final int PRINT = 3;
  public static final int AWAIT = 35;
  public static final int IMPORT = 27;
  public static final int IS = 8;
  public static final int MINUS = 43;
  public static final int IN = 38;
  public static final int OR = 6;
  public static final int error = 1;
  public static final int NOT_EQUAL = 49;
  public static final int FINALLY = 19;
  public static final int DOUBLE_EQUAL = 48;
  public static final int CONTINUE = 15;
  public static final int IF = 9;
  public static final int CAST_FLOAT = 77;
  public static final int GREATER_EQUAL = 53;
  public static final int COLON = 57;
  public static final int ASSERT = 21;
  public static final int LESS_EQUAL = 52;
  public static final int RBRACKET = 62;
  public static final int GLOBAL = 31;
  public static final int CAST_INT = 76;
  public static final int CASE = 68;
  public static final int STRING = 72;
  public static final int RANGE = 39;
  public static final int AND = 5;
  public static final int UMINUS = 44;
  public static final int LBRACKET = 61;
  public static final int WITH = 32;
}

