
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 01 13:49:13 CST 2025
//----------------------------------------------------

package practica4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 29;
  public static final int IDENTIFIER = 63;
  public static final int FROM = 28;
  public static final int LESS_THAN = 46;
  public static final int GREATER_THAN = 47;
  public static final int ASYNC = 34;
  public static final int RAISE = 20;
  public static final int NONLOCAL = 33;
  public static final int LAMBDA = 24;
  public static final int PASS = 16;
  public static final int COMMA = 54;
  public static final int STRING_SIMPLE = 67;
  public static final int RBRACE = 56;
  public static final int ELIF = 11;
  public static final int RPAREN = 62;
  public static final int INTEGER = 64;
  public static final int LBRACE = 55;
  public static final int LPAREN = 61;
  public static final int DEL = 30;
  public static final int YIELD = 25;
  public static final int FALSE = 3;
  public static final int NOT = 7;
  public static final int DEF = 22;
  public static final int FLOAT = 65;
  public static final int PACKAGE = 36;
  public static final int CLASS = 26;
  public static final int EXCEPT = 18;
  public static final int MULTIPLY = 41;
  public static final int PIPE = 60;
  public static final int TRUE = 2;
  public static final int MALFORMED_NUMBER = 70;
  public static final int PLUS = 39;
  public static final int DIVIDE = 42;
  public static final int WHILE = 13;
  public static final int EQUAL = 43;
  public static final int MODULE = 50;
  public static final int LINE_COMMENT = 37;
  public static final int CHAR = 68;
  public static final int NONE = 4;
  public static final int FOR = 12;
  public static final int RETURN = 23;
  public static final int BACK_SLASH = 59;
  public static final int ELSE = 10;
  public static final int TRY = 17;
  public static final int BREAK = 14;
  public static final int DOT = 51;
  public static final int EOF = 0;
  public static final int SEMICOLON = 52;
  public static final int MALFORMED_IDENTIFIER = 71;
  public static final int UNCLOSED_STRING = 69;
  public static final int AWAIT = 35;
  public static final int IMPORT = 27;
  public static final int IS = 8;
  public static final int MINUS = 40;
  public static final int IN = 38;
  public static final int OR = 6;
  public static final int error = 1;
  public static final int NOT_EQUAL = 45;
  public static final int FINALLY = 19;
  public static final int DOUBLE_EQUAL = 44;
  public static final int CONTINUE = 15;
  public static final int IF = 9;
  public static final int GREATER_EQUAL = 49;
  public static final int COLON = 53;
  public static final int ASSERT = 21;
  public static final int LESS_EQUAL = 48;
  public static final int RBRACKET = 58;
  public static final int GLOBAL = 31;
  public static final int STRING = 66;
  public static final int AND = 5;
  public static final int LBRACKET = 57;
  public static final int WITH = 32;
}

