
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 31 11:01:56 CST 2025
//----------------------------------------------------

package Actividad7;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 27;
  public static final int IDENTIFIER = 64;
  public static final int FROM = 26;
  public static final int LESS_THAN = 47;
  public static final int GREATER_THAN = 48;
  public static final int ASYNC = 32;
  public static final int RAISE = 18;
  public static final int NONLOCAL = 31;
  public static final int LAMBDA = 22;
  public static final int PASS = 14;
  public static final int INDENT = 38;
  public static final int COMMA = 55;
  public static final int STRING_SIMPLE = 68;
  public static final int DEDENT = 39;
  public static final int RBRACE = 57;
  public static final int CAST_BOOL = 74;
  public static final int ELIF = 9;
  public static final int RPAREN = 63;
  public static final int INTEGER = 65;
  public static final int LBRACE = 56;
  public static final int LPAREN = 62;
  public static final int DEL = 28;
  public static final int YIELD = 23;
  public static final int FALSE = 70;
  public static final int NOT = 5;
  public static final int DEF = 20;
  public static final int FLOAT = 66;
  public static final int PACKAGE = 34;
  public static final int CLASS = 24;
  public static final int EXCEPT = 16;
  public static final int MULTIPLY = 42;
  public static final int PIPE = 61;
  public static final int MALFORMED_NUMBER = 76;
  public static final int TRUE = 69;
  public static final int PLUS = 40;
  public static final int DIVIDE = 43;
  public static final int WHILE = 11;
  public static final int EQUAL = 44;
  public static final int MODULE = 51;
  public static final int LINE_COMMENT = 35;
  public static final int NONE = 2;
  public static final int FOR = 10;
  public static final int RETURN = 21;
  public static final int BACK_SLASH = 60;
  public static final int ELSE = 8;
  public static final int TRY = 15;
  public static final int BREAK = 12;
  public static final int CAST_STR = 73;
  public static final int DOT = 52;
  public static final int EOF = 0;
  public static final int SEMICOLON = 53;
  public static final int MALFORMED_IDENTIFIER = 77;
  public static final int UNCLOSED_STRING = 75;
  public static final int AWAIT = 33;
  public static final int IMPORT = 25;
  public static final int IS = 6;
  public static final int MINUS = 41;
  public static final int IN = 36;
  public static final int OR = 4;
  public static final int error = 1;
  public static final int NOT_EQUAL = 46;
  public static final int FINALLY = 17;
  public static final int DOUBLE_EQUAL = 45;
  public static final int CONTINUE = 13;
  public static final int IF = 7;
  public static final int CAST_FLOAT = 72;
  public static final int GREATER_EQUAL = 50;
  public static final int COLON = 54;
  public static final int ASSERT = 19;
  public static final int LESS_EQUAL = 49;
  public static final int RBRACKET = 59;
  public static final int GLOBAL = 29;
  public static final int CAST_INT = 71;
  public static final int STRING = 67;
  public static final int RANGE = 37;
  public static final int AND = 3;
  public static final int LBRACKET = 58;
  public static final int WITH = 30;
}

